# Generated by Django 6.1.1 on 2026-10-05 15:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_existing_responses(apps, schema_editor):
    Quote = apps.get_model("quotes", "Quote")
    Notification = apps.get_model("quotes", "QuoteNotification")
    database = schema_editor.connection.alias
    pending = []
    quotes = Quote.objects.using(database).filter(
        status__in=["ACCEPTED", "REJECTED"],
    ).select_related("customer")
    for quote in quotes.iterator(chunk_size=1000):
        responded_at = quote.accepted_at if quote.status == "ACCEPTED" else quote.rejected_at
        pending.append(Notification(
            user_id=quote.customer.user_id,
            quote_id=quote.pk,
            status=quote.status,
            quote_title=quote.title,
            customer_name=quote.customer.name,
            created_at=responded_at or quote.updated_at,
        ))
        if len(pending) == 1000:
            Notification.objects.using(database).bulk_create(pending)
            pending = []
    if pending:
        Notification.objects.using(database).bulk_create(pending)


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accettato'), ('REJECTED', 'Rifiutato')], max_length=20)),
                ('quote_title', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('quote', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_notification', to='quotes.quote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'read_at', '-created_at'], name='quotes_quot_user_id_063eeb_idx')],
            },
        ),
        migrations.RunPython(seed_existing_responses, migrations.RunPython.noop),
    ]
