# Generated by Django 6.1.1 on 2026-10-06 07:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quotenotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('after_days', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
            ],
        ),
        migrations.AlterField(
            model_name='quotenotification',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='quotes.quote'),
        ),
        migrations.AlterField(
            model_name='quotenotification',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accettato'), ('REJECTED', 'Rifiutato'), ('REMINDER', 'Da sollecitare')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='quotenotification',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'REMINDER')), fields=('quote',), name='unique_quote_reminder'),
        ),
        migrations.AddConstraint(
            model_name='quotenotification',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACCEPTED', 'REJECTED'])), fields=('quote',), name='unique_quote_response'),
        ),
        migrations.AddField(
            model_name='quoteremindersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_reminder_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='quoteremindersettings',
            constraint=models.CheckConstraint(condition=models.Q(('after_days__gte', 1), ('after_days__lte', 365)), name='quote_reminder_days_range'),
        ),
    ]
