# Generated by Django 6.1.1 on 2026-10-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='company_profile_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
