# Generated by Django 6.1.1 on 2026-10-06 17:03

import django.core.validators
from django.db import migrations, models
from django.db.models.functions import Floor


def check_existing_quantities(apps, schema_editor):
    QuoteItem = apps.get_model('quotes', 'QuoteItem')
    # Impedisce scritture tra il controllo e la conversione nella stessa transazione.
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f'LOCK TABLE {schema_editor.quote_name(QuoteItem._meta.db_table)} '
            'IN ACCESS EXCLUSIVE MODE'
        )

    invalid = QuoteItem.objects.using(schema_editor.connection.alias).filter(
        models.Q(quantity__lt=1)
        | models.Q(quantity__gt=99999999)
        | ~models.Q(quantity=Floor(models.F('quantity')))
    )
    examples = list(invalid.values_list('id', 'quantity')[:10])
    if examples:
        raise RuntimeError(
            'Migrazione interrotta: esistono quantità frazionarie o fuori '
            f'intervallo (1–99999999). Voci da verificare (id, quantità): {examples}. '
            'Nessun dato è stato modificato.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_company_profile_snapshot'),
    ]

    operations = [
        migrations.RunPython(check_existing_quantities, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='quoteitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AddConstraint(
            model_name='quoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 99999999)), name='quote_item_quantity_range'),
        ),
    ]
